### ISSUE TITLE
Load test is looking for edge router

### ISSUE THREAD

**Issue by abuehrle** [microservices-demo/load-test#11]
Installing on bare metal server, and try to run the loadtest with the following: 

```docker run -ti --rm --name=LOAD_TEST   weaveworksdemos/load-test -h edge-router -r 100 -c 2 host IP: node-port```

returns:  Locust file: /config/locustfile.py
edge-router is not accessible

**Comment by vlal** [comment]
@abuehrle is the edge-router running? could add a `-d <secs>` to the arguments to introduce a delay?

**Comment by abuehrle** [comment]
It wasn't working in a prior version of the sockshop, but I downloaded a newer version and it seems to be working.   Is there a way to see what version of the sockshop I am running, btw?

**Comment by nustiueudinastea** [comment]
@abuehrle unfortunately there is no version for the whole Sock Shop. At the moment you can only see the versions of the individual containers that make up the whole application. Will close since this is not an issue anymore.
