### ISSUE TITLE
Review comprehensive nature of loadtest

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/load-test#14]
Right now it often seems to be missing whole chunks for long periods of time (or even forever).

Insure that the endpoint tests are comprehensive across all services and steady.

**Comment by rade** [comment]
> steady

A little bit of variance - the odd connection coming and going - is fine, and arguably quite good, since it shows that we are showing realtime info.

**Comment by pidster** [comment]
Micro Sock shows the expected topology:

<img width="1051" alt="micro-sock-graph" src="https://cloud.githubusercontent.com/assets/303151/24106072/c0db24f2-0d7e-11e7-847f-55537b62a11a.png">

The load test should also lead to a nearly identical graph being formed.

**Comment by vlal** [comment]
Seems to be working as expected now.

![screen shot 2017-03-20 at 4 12 30 pm](https://cloud.githubusercontent.com/assets/596206/24106433/1a18b508-0d88-11e7-8ead-6ae612add710.png)

**Comment by rade** [comment]
Nice! Watching it for a few minutes, I can occasionally see frontend->user and frontend->carts connections. Are these real, or some scope glitch? If they are real, then that's exactly the right level of variance to illustrate that it's "live"; so well done :)

**Comment by jasonrichardsmith** [comment]
Can we close this issue? @rade

**Comment by rade** [comment]
> Can we close this issue? @rade

Nope. Here's what I am seeing right now:
![screenshot_2017-03-22_12-06-23](https://cloud.githubusercontent.com/assets/109109/24197095/2100885c-0ef8-11e7-8e2e-35f94f0db272.png)

**Comment by jasonrichardsmith** [comment]
@rade 
I am showing connections being made and going away.

https://www.youtube.com/watch?v=7zwwHCuiEsE

**Comment by rade** [comment]
>  I am showing connections being made and going away.

Yep. And some of that is fine. But there is way too much of it going on. Large chunks of the system become disconnected for some time. I've just tried it again.

Btw, note that the layout in the youtube vid looks nothing like what @pidster and @vlal posted above, though hitting 'redraw' would probably correct most of that and also make it easier for you to see when the "chunks become disconnected" happens.

**Comment by lukemarsden** [comment]
@rade 

I've just taken a look at this in staging and it looks fine to me now. We can't have _variance_ *and* a completely connected graph at all times.

**Comment by rade** [comment]
I said the variance was optional. Give me a fully connected graph all the time first. Then dial it back.

No, it's not fine as is.

**Comment by lukemarsden** [comment]
I'll take another look.

**Comment by lukemarsden** [comment]
@vlal can you take a look at staging? If you watch the "services" view of staging for long enough, you'll see things become disconnected.

What delays and concurrency do you have configured on the load test at the moment? Can we do the prime number thing to avoid overlapping gaps?

**Comment by lukemarsden** [comment]
Let's aim for fully connected all the time for now.

**Comment by jasonrichardsmith** [comment]
closing, add to dx board if determined a priority
